name: EsquiloSpeak-local
values:
  - key: baseUrl
    value: 'http://localhost:8080/api/v1'
  - key: accessToken
    value: ''
  - key: courseId
    value: en_for_vi
  - key: lessonId
    value: lesson_101
  - key: questionId
    value: q_201
  - key: clientRequestId
    value: req_postman_test_123
  - key: deviceId
    value: device_postman_test
