CREATE SCHEMA IF NOT EXISTS content_schema;

CREATE TABLE content_schema.courses (
    course_id character varying(50) NOT NULL,
    created_at timestamp(6) without time zone,
    level character varying(10),
    source_language character varying(10) NOT NULL,
    target_language character varying(10) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT courses_pkey PRIMARY KEY (course_id)
);

CREATE TABLE content_schema.lessons (
    lesson_id character varying(50) NOT NULL,
    sequence_order integer NOT NULL,
    title character varying(255) NOT NULL,
    unit_id character varying(50) NOT NULL,
    version_id character varying(50),
    CONSTRAINT lessons_pkey PRIMARY KEY (lesson_id)
);

CREATE TABLE content_schema.questions (
    question_id character varying(50) NOT NULL,
    audio_url character varying(500),
    correct_answer character varying(255),
    explanation character varying(255),
    lesson_id character varying(50) NOT NULL,
    prompt character varying(255) NOT NULL,
    type character varying(50) NOT NULL,
    version_id character varying(50),
    CONSTRAINT questions_pkey PRIMARY KEY (question_id)
);

CREATE TABLE content_schema.question_options (
    option_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    option_text character varying(255) NOT NULL,
    question_id character varying(50),
    CONSTRAINT question_options_pkey PRIMARY KEY (option_id),
    CONSTRAINT fksb9v00wdrgc9qojtjkv7e1gkp FOREIGN KEY (question_id) REFERENCES content_schema.questions(question_id)
);

CREATE TABLE content_schema.units (
    unit_id character varying(50) NOT NULL,
    course_id character varying(50) NOT NULL,
    sequence_order integer NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT units_pkey PRIMARY KEY (unit_id)
);
