CREATE SCHEMA IF NOT EXISTS auth_schema;
CREATE SCHEMA IF NOT EXISTS user_schema;
CREATE SCHEMA IF NOT EXISTS content_schema;
CREATE SCHEMA IF NOT EXISTS learning_schema;
CREATE SCHEMA IF NOT EXISTS review_schema;
CREATE SCHEMA IF NOT EXISTS media_schema;
CREATE SCHEMA IF NOT EXISTS sync_schema;

